# Week 1: Intro to Python for Data Science (Data Types, Data Structures)

In [1]:
#First Program
print("learning python for data science")

learning python for data science


## data types in python

In [0]:
# 1: (int for Integer)
# 2.34: (float for Real number)
# "hello": (Str for String)
# TRUE/FALSE: (bool for Boolean)

In [3]:
type("Hello")
type(3.44)

float

In [0]:
# code for getting multiple outputs from a jupyter cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
type("Hello")
type(3.44)

str

float

In [6]:
type(3)

int

In [7]:
type(True)

bool

### Operations and Variables

#### Operations
#Basic mathematical operations can be used as it is in Python

In [8]:
30+44+12

86

In [9]:
12-33

-21

In [10]:
8*2

16

In [11]:
4/3

1.3333333333333333

#### Variables
#Variable is a memory location in python to store values

In [12]:
var = 38
print(var)

38


In [13]:
time_in_mins = 233
time_in_hours = time_in_mins/60
print(time_in_hours)

3.8833333333333333


In [14]:
x = 3 
y = 6
z = y/x
print(z)

2.0


### String operations

In [15]:
# Define a string and assign its value to a variable named Place
Place = "UnitedStates"
print(Place)

UnitedStates


In [16]:
# Indexing in Python starts from 0. 
# Reason : Index n signifies a memory location that is n-elements away from the starting element.

print(Place[0])

U


In [17]:
# Negative indexing (counting backwards)
print(Place[-1])
print(Place[-7:-1])
print(Place[-9])
print(Place[-13])

s
dState
t


IndexError: ignored

In [18]:
len(Place)

12

In [19]:
Place[0:3]

'Uni'

In [20]:
Place[4:6]

'ed'

In [21]:
fact = Place + " America"
fact

'UnitedStates America'

In [22]:
X=fact
print("before upper:",X)
Y= X.upper()
print("After upper:",Y)

before upper: UnitedStates America
After upper: UNITEDSTATES AMERICA


In [23]:
X

'UnitedStates America'

In [24]:
Y=X.replace('UnitedStates ', 'Z')
Y

'ZAmerica'

In [0]:
Y = Y.replace('i',"")

In [27]:
print(Y)

ZAmerca


In [28]:
len(X)

20

In [29]:
X

'UnitedStates America'

In [30]:
X.find('America')

13

In [31]:
X[-1]

'a'

## Python : Data Structures

#In python, everything is an object. An object is collection of data points / variables.
#Data structures for organizing, manipulating, storing data
#4 major data structures : list, dictionaries, tuples, sets

### Lists 
#In list order stays same and item can be accessed using its position.

In [0]:
metros = ['Bengaluru','Mumbai','Delhi']

In [33]:
metros[1]

'Mumbai'

In [34]:
type(metros)

list

In [35]:
len(metros)

3

In [36]:
metros.append("Pune")
metros

['Bengaluru', 'Mumbai', 'Delhi', 'Pune']

In [37]:
metros.pop(1)

'Mumbai'

In [38]:
metros

['Bengaluru', 'Delhi', 'Pune']

### Dictionaries
#Unordered and values are accessed by keys. Dictionaries have key-value pairs

In [0]:
Planet_locations = { 
  'Mars': 4, # a key-value pair
  'Earth': 3,
  'Venus': 2,
}

In [40]:
Planet_locations.keys()

dict_keys(['Mars', 'Earth', 'Venus'])

In [41]:
# getting the dta type of dictionary
type(Planet_locations)

dict

In [42]:
Planet_locations.values()

dict_values([4, 3, 2])

In [43]:
type(Planet_locations.keys())

dict_keys

### Tuples
#work like lists except they are immutable which means they can’t be changed in place.

In [44]:
p = (1, ) 
q = ('t', 4, 3, 2) 
r = ('A', ('B', 'C'))   #Nested Tuple
len(p) 

1

In [45]:
type(p)

tuple

In [46]:
r[1]
r[1][0]

('B', 'C')

'B'

### Sets
#Collection of unique items in an unordered and unindexed manner. 
#Set operations like union, intersection work on them

In [47]:
# Defining 2 sets
Planets = {'venus','Earth','Mars'}
locations = {2,3,4}
Planet_locations = Planets.union(locations)
Planets
locations
Planet_locations

{'Earth', 'Mars', 'venus'}

{2, 3, 4}

{2, 3, 4, 'Earth', 'Mars', 'venus'}

## NumPy and pandas libraries

In [0]:
#Numpy(Numerical Python) is a mathematical library and its helpful as its allow to use arrays in python.

In [49]:
import numpy as np
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [50]:
a = np.random.randint(0,50,size=(50, 5))
a

array([[16, 49, 27,  4, 48],
       [22,  2, 40, 38, 46],
       [49,  4, 13, 36, 33],
       [26, 14, 43, 12, 22],
       [31, 17,  2, 48, 16],
       [ 1, 34, 19, 45,  5],
       [43, 35, 38, 45, 25],
       [ 5, 23, 24,  9, 20],
       [ 5,  3, 19, 38, 37],
       [43, 18,  9, 21, 15],
       [10, 35, 49, 30, 19],
       [42, 10, 21,  2, 29],
       [49, 41, 47, 11, 48],
       [24, 32, 10, 23, 17],
       [30, 13,  2, 13, 28],
       [39, 38, 13, 39, 16],
       [10, 16, 47, 35, 13],
       [47, 40, 14, 35, 41],
       [49, 25, 14,  3,  1],
       [13, 23, 46,  8, 38],
       [34, 34, 45, 10, 34],
       [14, 23, 47, 39, 41],
       [47, 21, 41,  5, 22],
       [38, 16, 25,  5, 45],
       [ 6, 41, 41, 40, 26],
       [22, 30, 11, 19, 36],
       [49, 41, 31, 16, 13],
       [37, 38, 46, 12, 32],
       [30, 15, 46, 42, 12],
       [10, 28, 36,  2, 24],
       [20, 23, 24, 17, 43],
       [23, 24,  2, 15, 28],
       [ 5,  8, 31, 43, 39],
       [36, 36, 11, 35, 46],
       [19,  6

### pandas DataFrame
#pandas is a python library mainly used for data manipulation. DataFrame is its key data structure. 
#Its similar to data table, database, spreadsheet 

In [51]:
import pandas as pd 

# Create the pandas DataFrame 

df = pd.DataFrame(a, columns=list('PQRST'))
df

P   Q   R   S   T
0   16  49  27   4  48
1   22   2  40  38  46
2   49   4  13  36  33
3   26  14  43  12  22
4   31  17   2  48  16
5    1  34  19  45   5
6   43  35  38  45  25
7    5  23  24   9  20
8    5   3  19  38  37
9   43  18   9  21  15
10  10  35  49  30  19
11  42  10  21   2  29
12  49  41  47  11  48
13  24  32  10  23  17
14  30  13   2  13  28
15  39  38  13  39  16
16  10  16  47  35  13
17  47  40  14  35  41
18  49  25  14   3   1
19  13  23  46   8  38
20  34  34  45  10  34
21  14  23  47  39  41
22  47  21  41   5  22
23  38  16  25   5  45
24   6  41  41  40  26
25  22  30  11  19  36
26  49  41  31  16  13
27  37  38  46  12  32
28  30  15  46  42  12
29  10  28  36   2  24
30  20  23  24  17  43
31  23  24   2  15  28
32   5   8  31  43  39
33  36  36  11  35  46
34  19   6  15  14  32
35   2  42  38  27  40
36  26  39  26  22   6
37  39  17  14  19   8
38  26  29  19  24  44
39  28  12  35  17  34
40  37  16  17  31  36
41  11  36  35  29  17
42  10  20   9   3  28
43  42  21  37  22  48
44  39  49   4   1  25
45  26  23  38  33  12
46   0  29  49  19  38
47  24  23  43  25  46
48  27   4   6  20   8
49  12  49  14  11   3

In [52]:
df.head()
df.tail()

P   Q   R   S   T
0  16  49  27   4  48
1  22   2  40  38  46
2  49   4  13  36  33
3  26  14  43  12  22
4  31  17   2  48  16

P   Q   R   S   T
45  26  23  38  33  12
46   0  29  49  19  38
47  24  23  43  25  46
48  27   4   6  20   8
49  12  49  14  11   3

In [53]:
type(df)

pandas.core.frame.DataFrame

In [54]:
df.columns

Index(['P', 'Q', 'R', 'S', 'T'], dtype='object')

In [55]:
# (rows,columns)
df.shape

(50, 5)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   P       50 non-null     int64
 1   Q       50 non-null     int64
 2   R       50 non-null     int64
 3   S       50 non-null     int64
 4   T       50 non-null     int64
dtypes: int64(5)
memory usage: 2.1 KB


In [57]:
# statistical summary of numeric columns
df.describe()
df.describe(percentiles=[0.44,0.99])

P          Q          R          S          T
count  50.000000  50.000000  50.000000  50.000000  50.000000
mean   25.860000  25.300000  26.660000  22.240000  27.660000
std    14.844789  12.828937  15.120752  13.680852  13.673466
min     0.000000   2.000000   2.000000   1.000000   1.000000
25%    12.250000  16.000000  14.000000  11.250000  16.250000
50%    26.000000  23.000000  25.500000  20.500000  28.000000
75%    38.750000  35.750000  40.750000  35.000000  38.750000
max    49.000000  49.000000  49.000000  48.000000  48.000000

P          Q          R          S          T
count  50.000000  50.000000  50.000000  50.000000  50.000000
mean   25.860000  25.300000  26.660000  22.240000  27.660000
std    14.844789  12.828937  15.120752  13.680852  13.673466
min     0.000000   2.000000   2.000000   1.000000   1.000000
44%    24.000000  23.000000  22.680000  19.000000  25.560000
50%    26.000000  23.000000  25.500000  20.500000  28.000000
99%    49.000000  49.000000  49.000000  46.530000  48.000000
max    49.000000  49.000000  49.000000  48.000000  48.000000

In [58]:
df.P.value_counts()

49    4
26    4
10    4
39    3
5     3
43    2
42    2
37    2
22    2
47    2
30    2
24    2
12    1
6     1
11    1
14    1
2     1
1     1
13    1
23    1
16    1
19    1
20    1
27    1
28    1
31    1
34    1
36    1
38    1
0     1
Name: P, dtype: int64

In [59]:
df.P.unique()
df.P.nunique()

array([16, 22, 49, 26, 31,  1, 43,  5, 10, 42, 24, 30, 39, 47, 13, 34, 14,
       38,  6, 37, 20, 23, 36, 19,  2, 28, 11,  0, 27, 12])

30

In [60]:
df.Q.nunique()

31